var searchData=
[
  ['c_20api_0',['List of Matlab functions and corresponding C++ API',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md42',1,'']]],
  ['c_20functions_1',['Commands and corresponding C++ functions',['../md_Doxygen_2InterfaceCLI.html#autotoc_md36',1,'']]],
  ['capabilities_2',['capabilities',['../group__TasmanianAddons.html',1,'Additional Capabilities'],['../md_Doxygen_2InterfaceFortran2003.html#autotoc_md63',1,'MPI Fortran Capabilities']]],
  ['cite_20us_3',['Please cite us',['../index.html#autotoc_md4',1,'']]],
  ['class_4',['Sparse Grid Class',['../group__TasmanianSGClass.html',1,'']]],
  ['clear_5',['clear',['../classTasDREAM_1_1DistributedPosterior.html#a73eccf8f8997a64c0d078e683557fc8f',1,'TasDREAM::DistributedPosterior']]],
  ['clearbestparticles_6',['clearBestParticles',['../classTasOptimization_1_1ParticleSwarmState.html#a4440ee6fab2d62bbcbce864ece6ac932',1,'TasOptimization::ParticleSwarmState']]],
  ['clearcache_7',['clearCache',['../classTasOptimization_1_1ParticleSwarmState.html#a50cdfc304c8ad42d2fffa1bd32a714d5',1,'TasOptimization::ParticleSwarmState']]],
  ['clearconformaltransform_8',['clearConformalTransform',['../classTasGrid_1_1TasmanianSparseGrid.html#a77a93ed0f926ddcde829809ec21cbeb3',1,'TasGrid::TasmanianSparseGrid']]],
  ['cleardomaintransform_9',['clearDomainTransform',['../classTasGrid_1_1TasmanianSparseGrid.html#a6c9056f3c6e2b19d85863c81b8c41aea',1,'TasGrid::TasmanianSparseGrid']]],
  ['clearhistory_10',['clearHistory',['../classTasDREAM_1_1TasmanianDREAM.html#af66ecf36222f5652ac187f1764931178',1,'TasDREAM::TasmanianDREAM']]],
  ['clearlevellimits_11',['clearLevelLimits',['../classTasGrid_1_1TasmanianSparseGrid.html#a724e63b8ccccdf44169a6433cb2fa97c',1,'TasGrid::TasmanianSparseGrid']]],
  ['clearpdfvalues_12',['clearPDFvalues',['../classTasDREAM_1_1TasmanianDREAM.html#ab28a35d15bae366cd62a1de80e89e239',1,'TasDREAM::TasmanianDREAM']]],
  ['clearrefinement_13',['clearRefinement',['../classTasGrid_1_1TasmanianSparseGrid.html#aa2c461cb4699df8844812e6bf9f23872',1,'TasGrid::TasmanianSparseGrid']]],
  ['cmake_20package_20config_14',['Linking to Tasmanian: CMake Package Config',['../md_Doxygen_2Installation.html#autotoc_md20',1,'']]],
  ['cmake_3a_20the_20preferred_20way_15',['Install using CMake: the preferred way',['../md_Doxygen_2Installation.html#autotoc_md13',1,'']]],
  ['column_20format_16',['Row-vs-Column Format',['../md_Doxygen_2InterfaceFortran2003.html#autotoc_md60',1,'']]],
  ['command_20line_20interface_17',['Command Line Interface',['../md_Doxygen_2InterfaceCLI.html',1,'']]],
  ['command_3a_20h_20help_20help_20ndash_20help_18',['Command: -h, help, -help, &amp;ndash;help',['../md_Doxygen_2InterfaceCLI.html#autotoc_md35',1,'']]],
  ['command_3a_20listtypes_19',['Command: -listtypes',['../md_Doxygen_2InterfaceCLI.html#autotoc_md37',1,'']]],
  ['command_3a_20test_20',['Command: -test',['../md_Doxygen_2InterfaceCLI.html#autotoc_md39',1,'']]],
  ['command_3a_20version_20or_20info_21',['Command: -version or -info',['../md_Doxygen_2InterfaceCLI.html#autotoc_md38',1,'']]],
  ['commands_22',['Example commands',['../md_Doxygen_2InterfaceCLI.html#autotoc_md34',1,'']]],
  ['commands_20and_20corresponding_20c_20functions_23',['Commands and corresponding C++ functions',['../md_Doxygen_2InterfaceCLI.html#autotoc_md36',1,'']]],
  ['complex_20numbers_24',['Complex numbers',['../md_Doxygen_2InterfaceFortran2003.html#autotoc_md62',1,'']]],
  ['computestationarityresidual_25',['computeStationarityResidual',['../group__OptimizationUtil.html#gaa27bd012848274c59d0406c253d1e878',1,'TasOptimization']]],
  ['config_26',['Linking to Tasmanian: CMake Package Config',['../md_Doxygen_2Installation.html#autotoc_md20',1,'']]],
  ['const_5fone_27',['const_one',['../group__DREAMSampleCore.html#ga72d96d12972b7baca992d9fc4f9ed7d4',1,'TasDREAM']]],
  ['const_5fpercent_28',['const_percent',['../group__DREAMSampleCore.html#ga1c17682f1d9e0eb669a74cbd6c5fadfa',1,'TasDREAM']]],
  ['construction_20procedure_29',['construction procedure',['../group__TasmanianAddonsConstruct.html',1,'Automated Surrogate Construction Procedure'],['../group__TasmanianAddonsMPIConstruct.html',1,'MPI Automated Surrogate Construction Procedure']]],
  ['constructsurrogate_30',['constructsurrogate',['../group__TasmanianAddonsConstruct.html#ga4ed57c25a9f903ce06604091bd1fe500',1,'TasGrid::constructSurrogate(ModelSignature model, size_t max_num_points, size_t num_parallel_jobs, size_t max_samples_per_job, TasmanianSparseGrid &amp;grid, TypeDepth type, int output, std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;(), std::string const &amp;checkpoint_filename=std::string())'],['../group__TasmanianAddonsConstruct.html#gac0788f48fb2593d686d3b2173f5821f0',1,'TasGrid::constructSurrogate(ModelSignature model, size_t max_num_points, size_t num_parallel_jobs, size_t max_samples_per_job, TasmanianSparseGrid &amp;grid, TypeDepth type, std::vector&lt; int &gt; const &amp;anisotropic_weights=std::vector&lt; int &gt;(), std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;(), std::string const &amp;checkpoint_filename=std::string())'],['../group__TasmanianAddonsConstruct.html#ga868eb3d17df0eefb438376c92002b8de',1,'TasGrid::constructSurrogate(ModelSignature model, size_t max_num_points, size_t num_parallel_jobs, size_t max_samples_per_job, TasmanianSparseGrid &amp;grid, double tolerance, TypeRefinement criteria, int output=-1, std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;(), std::string const &amp;checkpoint_filename=std::string())']]],
  ['contributors_31',['contributors',['../md_Doxygen_2Contributors.html#autotoc_md8',1,'Current Contributors'],['../md_Doxygen_2Contributors.html#autotoc_md9',1,'Former Contributors']]],
  ['copygrid_32',['copygrid',['../group__TasmanianSG.html#gae7dff1a79964aa775e372b615e07ef44',1,'TasGrid::copyGrid()'],['../classTasGrid_1_1TasmanianSparseGrid.html#aad72b8b49644b0cd6a2e7acf6b51875b',1,'TasGrid::TasmanianSparseGrid::copyGrid(TasmanianSparseGrid const &amp;source, int outputs_begin=0, int outputs_end=-1)'],['../classTasGrid_1_1TasmanianSparseGrid.html#a57fef46babb671c68ed6375da9d96a61',1,'TasGrid::TasmanianSparseGrid::copyGrid(const TasmanianSparseGrid *source, int outputs_begin=0, int outputs_end=-1)']]],
  ['corresponding_20c_20api_33',['List of Matlab functions and corresponding C++ API',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md42',1,'']]],
  ['corresponding_20c_20functions_34',['Commands and corresponding C++ functions',['../md_Doxygen_2InterfaceCLI.html#autotoc_md36',1,'']]],
  ['current_20contributors_35',['Current Contributors',['../md_Doxygen_2Contributors.html#autotoc_md8',1,'']]],
  ['custom_20rule_20file_20format_36',['Custom Rule File Format',['../md_Doxygen_2CustomRuleFileFormat.html',1,'']]]
];
