var searchData=
[
  ['libensemble_20integration_0',['libEnsemble Integration',['../md_Doxygen_2InterfaceLibEnsemble.html',1,'']]],
  ['likelihood_20definitions_1',['Likelihood definitions',['../group__DREAMLikelihood.html',1,'']]],
  ['likelihoodgaussanisotropic_2',['likelihoodgaussanisotropic',['../classTasDREAM_1_1LikelihoodGaussAnisotropic.html#a4ea02ebe86c3271d5f28c858d4c23442',1,'TasDREAM::LikelihoodGaussAnisotropic::LikelihoodGaussAnisotropic()=default'],['../classTasDREAM_1_1LikelihoodGaussAnisotropic.html#a6e90e9d40f5cc3f53b14f83589e52c48',1,'TasDREAM::LikelihoodGaussAnisotropic::LikelihoodGaussAnisotropic(std::vector&lt; double &gt; const &amp;variance, std::vector&lt; double &gt; const &amp;data_mean, size_t num_observe=1)'],['../classTasDREAM_1_1LikelihoodGaussAnisotropic.html',1,'TasDREAM::LikelihoodGaussAnisotropic']]],
  ['likelihoodgaussisotropic_3',['likelihoodgaussisotropic',['../classTasDREAM_1_1LikelihoodGaussIsotropic.html',1,'TasDREAM::LikelihoodGaussIsotropic'],['../classTasDREAM_1_1LikelihoodGaussIsotropic.html#a7e254516ff7b153c999092f420047645',1,'TasDREAM::LikelihoodGaussIsotropic::LikelihoodGaussIsotropic()'],['../classTasDREAM_1_1LikelihoodGaussIsotropic.html#a49f5d823abacb9c1d326634eee8eaa21',1,'TasDREAM::LikelihoodGaussIsotropic::LikelihoodGaussIsotropic(double variance, const std::vector&lt; double &gt; &amp;data_mean, size_t num_observe=1)']]],
  ['line_20interface_4',['Command Line Interface',['../md_Doxygen_2InterfaceCLI.html',1,'']]],
  ['linking_20to_20tasmanian_3a_20cmake_20package_20config_5',['Linking to Tasmanian: CMake Package Config',['../md_Doxygen_2Installation.html#autotoc_md20',1,'']]],
  ['list_20of_20matlab_20functions_20and_20corresponding_20c_20api_6',['List of Matlab functions and corresponding C++ API',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md42',1,'']]],
  ['listtypes_7',['Command: -listtypes',['../md_Doxygen_2InterfaceCLI.html#autotoc_md37',1,'']]],
  ['load_20from_20unstructured_20point_20set_8',['Load from Unstructured Point Set',['../group__TasmanianAddonsLoadUnstructured.html',1,'']]],
  ['load_20model_20values_9',['Static Load Model Values',['../group__TasmanianAddonsLoadNeededVals.html',1,'']]],
  ['loadconstructedpoints_10',['loadconstructedpoints',['../classTasGrid_1_1TasmanianSparseGrid.html#acc6df5aee38e3e41ecb01a19a0e0e5b3',1,'TasGrid::TasmanianSparseGrid::loadConstructedPoints(const double x[], int numx, const double y[])'],['../classTasGrid_1_1TasmanianSparseGrid.html#afa1f2b9ae8a96023bbf529a78173daee',1,'TasGrid::TasmanianSparseGrid::loadConstructedPoints(std::vector&lt; double &gt; const &amp;x, std::vector&lt; double &gt; const &amp;y)']]],
  ['loadneededpoints_11',['loadneededpoints',['../group__TasmanianAddonsLoadNeededVals.html#gad49a95d0766243ba2d5d1a8f10dedb15',1,'TasGrid::loadNeededPoints(std::function&lt; void(double const x[], double y[], size_t thread_id)&gt; model, TasmanianSparseGrid &amp;grid, size_t num_threads)'],['../group__TasmanianAddonsLoadNeededVals.html#ga765e36b8991244a94e3e57f48dcce874',1,'TasGrid::loadNeededPoints(std::function&lt; void(std::vector&lt; double &gt; const &amp;x, std::vector&lt; double &gt; &amp;y, size_t thread_id)&gt; model, TasmanianSparseGrid &amp;grid, size_t num_threads)'],['../classTasGrid_1_1TasmanianSparseGrid.html#aa7567a695e37d9c4188933653e35bf30',1,'TasGrid::TasmanianSparseGrid::loadNeededPoints(const double *vals)'],['../classTasGrid_1_1TasmanianSparseGrid.html#adcb888a2375dcbb51775b3a894eb32df',1,'TasGrid::TasmanianSparseGrid::loadNeededPoints(std::vector&lt; double &gt; const &amp;vals)']]],
  ['loadneededvalues_12',['loadneededvalues',['../classTasGrid_1_1TasmanianSparseGrid.html#a3217125cade60ca65e476f5a22531551',1,'TasGrid::TasmanianSparseGrid::loadNeededValues()'],['../group__TasmanianAddonsLoadNeededVals.html#gad239942d20e99244061b4886f96dea4a',1,'TasGrid::loadNeededValues(std::function&lt; void(double const x[], double y[], size_t thread_id)&gt; model, TasmanianSparseGrid &amp;grid, size_t num_threads)'],['../group__TasmanianAddonsLoadNeededVals.html#ga91382894cb86187d4a043af2f0d3c5c0',1,'TasGrid::loadNeededValues(std::function&lt; void(std::vector&lt; double &gt; const &amp;x, std::vector&lt; double &gt; &amp;y, size_t thread_id)&gt; model, TasmanianSparseGrid &amp;grid, size_t num_threads)'],['../classTasGrid_1_1TasmanianSparseGrid.html#af9a9e720271b111893fdcd7e70a4ff3e',1,'TasGrid::TasmanianSparseGrid::loadNeededValues()']]],
  ['loadunstructureddatal2_13',['loadunstructureddatal2',['../group__TasmanianAddonsLoadUnstructured.html#gaf6cc3abfc7b72c6258932ea149f11adf',1,'TasGrid::loadUnstructuredDataL2(double const data_points[], int num_data, double const model_values[], double tolerance, TasmanianSparseGrid &amp;grid)'],['../group__TasmanianAddonsLoadUnstructured.html#ga103f434b565f3f81a7d750d9fc57a1eb',1,'TasGrid::loadUnstructuredDataL2(std::vector&lt; double &gt; const &amp;data_points, std::vector&lt; double &gt; const &amp;model_values, double tolerance, TasmanianSparseGrid &amp;grid)']]],
  ['logform_14',['logform',['../group__DREAMEnumerates.html#gga71a406371701ba98394a923434395ff5ad662ab51216cd8c4f7cc6a832bc63e80',1,'TasDREAM']]]
];
