var searchData=
[
  ['uniform_5fprior_0',['uniform_prior',['../group__DREAMSampleCore.html#ga7100467a4cf3a6335fff1fe5f6a5a747',1,'TasDREAM']]],
  ['unstructured_20point_20set_1',['Load from Unstructured Point Set',['../group__TasmanianAddonsLoadUnstructured.html',1,'']]],
  ['updatefouriergrid_2',['updatefouriergrid',['../classTasGrid_1_1TasmanianSparseGrid.html#a67f090d1f36da85a708a0998bf30a188',1,'TasGrid::TasmanianSparseGrid::updateFourierGrid(int depth, TypeDepth type, std::vector&lt; int &gt; const &amp;anisotropic_weights, std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;())'],['../classTasGrid_1_1TasmanianSparseGrid.html#aae0e02a1708164d2f42ef319575f513d',1,'TasGrid::TasmanianSparseGrid::updateFourierGrid(int depth, TypeDepth type, const int *anisotropic_weights=nullptr, const int *level_limits=nullptr)']]],
  ['updateglobalgrid_3',['updateglobalgrid',['../classTasGrid_1_1TasmanianSparseGrid.html#aa3844fa4877ed768db7a25c70b207899',1,'TasGrid::TasmanianSparseGrid::updateGlobalGrid(int depth, TypeDepth type, std::vector&lt; int &gt; const &amp;anisotropic_weights, std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;())'],['../classTasGrid_1_1TasmanianSparseGrid.html#ae2a5e7d613d3101b31c2101c55d8f8f9',1,'TasGrid::TasmanianSparseGrid::updateGlobalGrid(int depth, TypeDepth type, const int *anisotropic_weights=nullptr, const int *level_limits=nullptr)']]],
  ['updategrid_4',['updategrid',['../classTasGrid_1_1TasmanianSparseGrid.html#ac54ac6202ec15150fd22f9c68bc9c920',1,'TasGrid::TasmanianSparseGrid::updateGrid(int depth, TypeDepth type, std::vector&lt; int &gt; const &amp;anisotropic_weights, std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;())'],['../classTasGrid_1_1TasmanianSparseGrid.html#a4a396b74c826a3cc6590ae41b740722d',1,'TasGrid::TasmanianSparseGrid::updateGrid(int depth, TypeDepth type, const int *anisotropic_weights=nullptr, const int *level_limits=nullptr)']]],
  ['updatesequencegrid_5',['updatesequencegrid',['../classTasGrid_1_1TasmanianSparseGrid.html#aaad3a5f9304cb39236f1bde2177a71ba',1,'TasGrid::TasmanianSparseGrid::updateSequenceGrid(int depth, TypeDepth type, std::vector&lt; int &gt; const &amp;anisotropic_weights, std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;())'],['../classTasGrid_1_1TasmanianSparseGrid.html#a13c25461dd243b59abd771b6ebb7c630',1,'TasGrid::TasmanianSparseGrid::updateSequenceGrid(int depth, TypeDepth type, const int *anisotropic_weights=nullptr, const int *level_limits=nullptr)']]],
  ['us_6',['Please cite us',['../index.html#autotoc_md4',1,'']]],
  ['usage_7',['Basic Usage',['../md_Doxygen_2InterfaceLibEnsemble.html#autotoc_md32',1,'']]],
  ['usage_20of_20tasmanian_8',['Basic Usage of Tasmanian',['../index.html#autotoc_md6',1,'']]],
  ['using_20cmake_3a_20the_20preferred_20way_9',['Install using CMake: the preferred way',['../md_Doxygen_2Installation.html#autotoc_md13',1,'']]],
  ['utility_20functions_20and_20aliases_10',['Miscellaneous utility functions and aliases',['../group__OptimizationUtil.html',1,'']]]
];
