var searchData=
[
  ['makeempty_0',['makeEmpty',['../group__TasmanianSG.html#ga0269d4c5c5352ef1f92cdde67b6ffcd7',1,'TasGrid']]],
  ['makefouriergrid_1',['makefouriergrid',['../classTasGrid_1_1TasmanianSparseGrid.html#abd80e501848d329413cd02d28ad29c59',1,'TasGrid::TasmanianSparseGrid::makeFourierGrid(int dimensions, int outputs, int depth, TypeDepth type, const int *anisotropic_weights=nullptr, const int *level_limits=nullptr)'],['../classTasGrid_1_1TasmanianSparseGrid.html#a2277a336a8e37728a61b5f2932487de2',1,'TasGrid::TasmanianSparseGrid::makeFourierGrid(int dimensions, int outputs, int depth, TypeDepth type, std::vector&lt; int &gt; const &amp;anisotropic_weights, std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;())'],['../group__TasmanianSG.html#ga946aedd76d776e8669671026911755d1',1,'TasGrid::makeFourierGrid(int dimensions, int outputs, int depth, TypeDepth type, std::vector&lt; int &gt; const &amp;anisotropic_weights=std::vector&lt; int &gt;(), std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;())']]],
  ['makeglobalgrid_2',['makeglobalgrid',['../group__TasmanianSG.html#ga734013b4f52c4d1d9a35d674b459e13a',1,'TasGrid::makeGlobalGrid()'],['../classTasGrid_1_1TasmanianSparseGrid.html#a1085ad2ff79ef2df0cf16cf31f54b451',1,'TasGrid::TasmanianSparseGrid::makeGlobalGrid(int dimensions, int outputs, int depth, TypeDepth type, CustomTabulated &amp;&amp;crule, const int *anisotropic_weights=nullptr, const int *level_limits=nullptr)'],['../classTasGrid_1_1TasmanianSparseGrid.html#a9790fc9925342d9416dbddb2342637d5',1,'TasGrid::TasmanianSparseGrid::makeGlobalGrid(int dimensions, int outputs, int depth, TypeDepth type, TypeOneDRule rule, std::vector&lt; int &gt; const &amp;anisotropic_weights, double alpha=0.0, double beta=0.0, const char *custom_filename=nullptr, std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;())'],['../classTasGrid_1_1TasmanianSparseGrid.html#a7714d84d823d00e8f4fbdcda34ed9a3d',1,'TasGrid::TasmanianSparseGrid::makeGlobalGrid(int dimensions, int outputs, int depth, TypeDepth type, TypeOneDRule rule, const int *anisotropic_weights=nullptr, double alpha=0.0, double beta=0.0, const char *custom_filename=nullptr, const int *level_limits=nullptr)'],['../classTasGrid_1_1TasmanianSparseGrid.html#a522a181d924f4427cb7c36421507090b',1,'TasGrid::TasmanianSparseGrid::makeGlobalGrid(int dimensions, int outputs, int depth, TypeDepth type, CustomTabulated &amp;&amp;crule, std::vector&lt; int &gt; const &amp;anisotropic_weights, std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;())']]],
  ['makelocalpolynomialgrid_3',['makelocalpolynomialgrid',['../classTasGrid_1_1TasmanianSparseGrid.html#aed3b81ba818620f88f7885186ec240a2',1,'TasGrid::TasmanianSparseGrid::makeLocalPolynomialGrid(int dimensions, int outputs, int depth, int order, TypeOneDRule rule, std::vector&lt; int &gt; const &amp;level_limits)'],['../classTasGrid_1_1TasmanianSparseGrid.html#a46de747af60e89360aae074d00161c0f',1,'TasGrid::TasmanianSparseGrid::makeLocalPolynomialGrid(int dimensions, int outputs, int depth, int order=1, TypeOneDRule rule=rule_localp, const int *level_limits=nullptr)'],['../group__TasmanianSG.html#gaaa84e44ca8145727564dbb57e7c939a3',1,'TasGrid::makeLocalPolynomialGrid()']]],
  ['makeobjectivefunction_4',['makeObjectiveFunction',['../group__OptimizationUtil.html#ga9c5629ee6b0c4786a1c477e305068743',1,'TasOptimization']]],
  ['makesequencegrid_5',['makesequencegrid',['../group__TasmanianSG.html#ga40cde16ae94c02a23271df606918cfb9',1,'TasGrid::makeSequenceGrid()'],['../classTasGrid_1_1TasmanianSparseGrid.html#a1f541f68b1e4b13fbc7dd31b1efd3fce',1,'TasGrid::TasmanianSparseGrid::makeSequenceGrid(int dimensions, int outputs, int depth, TypeDepth type, TypeOneDRule rule, const int *anisotropic_weights=nullptr, const int *level_limits=nullptr)'],['../classTasGrid_1_1TasmanianSparseGrid.html#add5d51d4a5cddb0753f8a38dee15fb18',1,'TasGrid::TasmanianSparseGrid::makeSequenceGrid(int dimensions, int outputs, int depth, TypeDepth type, TypeOneDRule rule, std::vector&lt; int &gt; const &amp;anisotropic_weights, std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;())']]],
  ['makewaveletgrid_6',['makewaveletgrid',['../classTasGrid_1_1TasmanianSparseGrid.html#adc8036abf3c59fe31212c21c700a4aeb',1,'TasGrid::TasmanianSparseGrid::makeWaveletGrid(int dimensions, int outputs, int depth, int order=1, const int *level_limits=nullptr)'],['../classTasGrid_1_1TasmanianSparseGrid.html#a35b09ba463727decb5c96e4040393641',1,'TasGrid::TasmanianSparseGrid::makeWaveletGrid(int dimensions, int outputs, int depth, int order, std::vector&lt; int &gt; const &amp;level_limits)'],['../group__TasmanianSG.html#ga39d644b025ba40d9dcfa6af96a0c7dad',1,'TasGrid::makeWaveletGrid()']]],
  ['mergerefinement_7',['mergeRefinement',['../classTasGrid_1_1TasmanianSparseGrid.html#aa5b56474f1ce23a77b0f62a7bd8c9ee3',1,'TasGrid::TasmanianSparseGrid']]],
  ['mpiconstructsurrogate_8',['mpiconstructsurrogate',['../group__TasmanianAddonsMPIConstruct.html#ga8bef49fcf53bfe96df8fb433e3cf4cc7',1,'TasGrid::mpiConstructSurrogate(ModelSignatureMPI model, int num_dimensions, int num_outputs, size_t max_num_points, size_t max_samples_per_job, size_t max_num_ranks, int tagx, int tagy, int root, MPI_Comm comm, TasmanianSparseGrid &amp;grid, TypeDepth type, int output, std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;(), std::string const &amp;checkpoint_filename=std::string())'],['../group__TasmanianAddonsMPIConstruct.html#gaeec04bf28521616e8082a73bb6c6baa2',1,'TasGrid::mpiConstructSurrogate(ModelSignatureMPI model, int num_dimensions, int num_outputs, size_t max_num_points, size_t max_samples_per_job, size_t max_num_ranks, int tagx, int tagy, int root, MPI_Comm comm, TasmanianSparseGrid &amp;grid, TypeDepth type, std::vector&lt; int &gt; const &amp;anisotropic_weights=std::vector&lt; int &gt;(), std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;(), std::string const &amp;checkpoint_filename=std::string())'],['../group__TasmanianAddonsMPIConstruct.html#ga959c5c21a2c9bffd485ac75f7098eafb',1,'TasGrid::mpiConstructSurrogate(ModelSignatureMPI model, int num_dimensions, int num_outputs, size_t max_num_points, size_t max_samples_per_job, size_t max_num_ranks, int tagx, int tagy, int root, MPI_Comm comm, TasmanianSparseGrid &amp;grid, double tolerance, TypeRefinement criteria, int output=-1, std::vector&lt; int &gt; const &amp;level_limits=std::vector&lt; int &gt;(), std::vector&lt; double &gt; const &amp;scale_correction=std::vector&lt; double &gt;(), std::string const &amp;checkpoint_filename=std::string())']]],
  ['mpiconstructworker_9',['mpiConstructWorker',['../group__TasmanianAddonsMPIConstruct.html#ga0472ab32a5ad7ee714ba5539db592932',1,'TasGrid']]],
  ['mpigridbcast_10',['MPIGridBcast',['../group__TasmanianAddonsMPIGridSend.html#gab9d57c01914cb9fc7b4b4719e242430b',1,'TasGrid']]],
  ['mpigridrecv_11',['MPIGridRecv',['../group__TasmanianAddonsMPIGridSend.html#ga5edceb66897460e5b9e104b624877cfc',1,'TasGrid']]],
  ['mpigridscatteroutputs_12',['MPIGridScatterOutputs',['../group__TasmanianAddonsMPIGridSend.html#ga11ebaf3d88e250fb6a08f8659e8b2a91',1,'TasGrid']]],
  ['mpigridsend_13',['MPIGridSend',['../group__TasmanianAddonsMPIGridSend.html#ga81fed6fbf2fd899aca4922646d2566d1',1,'TasGrid']]],
  ['mpilikelihoodrecv_14',['MPILikelihoodRecv',['../group__TasmanianAddonsMPIDREAMSend.html#ga205158d7910b9b923f7d6ac4e66121eb',1,'TasDREAM']]],
  ['mpilikelihoodscatter_15',['MPILikelihoodScatter',['../group__TasmanianAddonsMPIDREAMSend.html#ga2112fdeb5ed2ccddb49c45db5ec606ba',1,'TasDREAM']]],
  ['mpilikelihoodsend_16',['MPILikelihoodSend',['../group__TasmanianAddonsMPIDREAMSend.html#ga7c2e78b57e4fb7d83d78b8fc909ec5eb',1,'TasDREAM']]]
];
