var dir_63a9a72ba5f5353329101486f803cfa0 =
[
    [ "TasmanianSparseGrid.hpp", "TasmanianSparseGrid_8hpp_source.html", null ],
    [ "tsgAcceleratedDataStructures.hpp", "tsgAcceleratedDataStructures_8hpp_source.html", null ],
    [ "tsgAcceleratedHandles.hpp", "tsgAcceleratedHandles_8hpp_source.html", null ],
    [ "tsgCacheLagrange.hpp", "tsgCacheLagrange_8hpp_source.html", null ],
    [ "tsgCoreOneDimensional.hpp", "tsgCoreOneDimensional_8hpp_source.html", null ],
    [ "tsgCudaLoadStructures.hpp", "tsgCudaLoadStructures_8hpp_source.html", null ],
    [ "tsgDConstructGridGlobal.hpp", "tsgDConstructGridGlobal_8hpp_source.html", null ],
    [ "tsgEnumerates.hpp", "tsgEnumerates_8hpp_source.html", null ],
    [ "tsgGridCore.hpp", "tsgGridCore_8hpp_source.html", null ],
    [ "tsgGridFourier.hpp", "tsgGridFourier_8hpp_source.html", null ],
    [ "tsgGridGlobal.hpp", "tsgGridGlobal_8hpp_source.html", null ],
    [ "tsgGridLocalPolynomial.hpp", "tsgGridLocalPolynomial_8hpp_source.html", null ],
    [ "tsgGridSequence.hpp", "tsgGridSequence_8hpp_source.html", null ],
    [ "tsgGridWavelet.hpp", "tsgGridWavelet_8hpp_source.html", null ],
    [ "tsgHardCodedTabulatedRules.hpp", "tsgHardCodedTabulatedRules_8hpp_source.html", null ],
    [ "tsgHierarchyManipulator.hpp", "tsgHierarchyManipulator_8hpp_source.html", null ],
    [ "tsgIndexManipulator.hpp", "tsgIndexManipulator_8hpp_source.html", null ],
    [ "tsgIndexSets.hpp", "tsgIndexSets_8hpp_source.html", null ],
    [ "tsgIOHelpers.hpp", "tsgIOHelpers_8hpp_source.html", null ],
    [ "tsgLinearSolvers.hpp", "tsgLinearSolvers_8hpp_source.html", null ],
    [ "tsgMathUtils.hpp", "tsgMathUtils_8hpp_source.html", null ],
    [ "tsgOneDimensionalWrapper.hpp", "tsgOneDimensionalWrapper_8hpp_source.html", null ],
    [ "tsgRuleLocalPolynomial.hpp", "tsgRuleLocalPolynomial_8hpp_source.html", null ],
    [ "tsgRuleWavelet.hpp", "tsgRuleWavelet_8hpp_source.html", null ],
    [ "tsgSequenceOptimizer.hpp", "tsgSequenceOptimizer_8hpp_source.html", null ],
    [ "tsgUtils.hpp", "tsgUtils_8hpp_source.html", null ]
];