var group__Tasmanian =
[
    [ "Document Sections", "md_Doxygen_Installation.html#autotoc_md7", null ],
    [ "Requirements", "md_Doxygen_Installation.html#autotoc_md8", null ],
    [ "Install using CMake: the preferred way", "md_Doxygen_Installation.html#autotoc_md9", null ],
    [ "Install with the install script-wrapper around CMake", "md_Doxygen_Installation.html#autotoc_md10", null ],
    [ "Install with (basic) GNU Make", "md_Doxygen_Installation.html#autotoc_md11", null ],
    [ "Install with Python Pip", "md_Doxygen_Installation.html#autotoc_md12", null ],
    [ "Install with Spack", "md_Doxygen_Installation.html#autotoc_md13", null ],
    [ "Install on MS Windows platform", "md_Doxygen_Installation.html#autotoc_md14", null ],
    [ "Install folder structure", "md_Doxygen_Installation.html#autotoc_md15", null ],
    [ "Linking to Tasmanian: CMake Package Config", "md_Doxygen_Installation.html#autotoc_md16", null ],
    [ "Known Issues", "md_Doxygen_Installation.html#autotoc_md17", null ],
    [ "Requirements", "md_Doxygen_InterfacePython.html#autotoc_md19", null ],
    [ "Module", "md_Doxygen_InterfacePython.html#autotoc_md20", null ],
    [ "Additional Documentation", "md_Doxygen_InterfacePython.html#autotoc_md21", null ],
    [ "Error Handling", "md_Doxygen_InterfacePython.html#autotoc_md22", null ],
    [ "Acceleration and Thread Safety", "md_Doxygen_InterfacePython.html#autotoc_md23", null ],
    [ "Basic Plotting", "md_Doxygen_InterfacePython.html#autotoc_md24", null ],
    [ "Example commands", "md_Doxygen_InterfaceCLI.html#autotoc_md26", null ],
    [ "Command: -h, help, -help, –help", "md_Doxygen_InterfaceCLI.html#autotoc_md27", null ],
    [ "Commands and corresponding C++ functions", "md_Doxygen_InterfaceCLI.html#autotoc_md28", null ],
    [ "Command: -listtypes", "md_Doxygen_InterfaceCLI.html#autotoc_md29", null ],
    [ "Command: -version or -info", "md_Doxygen_InterfaceCLI.html#autotoc_md30", null ],
    [ "Command: -test", "md_Doxygen_InterfaceCLI.html#autotoc_md31", null ],
    [ "Matrix File Format", "md_Doxygen_InterfaceCLI.html#autotoc_md32", null ],
    [ "List of Matlab functions and corresponding C++ API", "md_Doxygen_InterfaceMATLAB.html#autotoc_md34", null ],
    [ "Function tsgCoreTests()", "md_Doxygen_InterfaceMATLAB.html#autotoc_md35", null ],
    [ "Function tsgGetPaths()", "md_Doxygen_InterfaceMATLAB.html#autotoc_md36", null ],
    [ "Function tsgReadMatrix() and tsgWriteMatrix()", "md_Doxygen_InterfaceMATLAB.html#autotoc_md37", null ],
    [ "Function tsgCleanTempFiles()", "md_Doxygen_InterfaceMATLAB.html#autotoc_md38", null ],
    [ "Function tsgListGridsByName()", "md_Doxygen_InterfaceMATLAB.html#autotoc_md39", null ],
    [ "Function tsgDeleteGrid()/tsgDeleteGridByName()", "md_Doxygen_InterfaceMATLAB.html#autotoc_md40", null ],
    [ "Function tsgReloadGrid()", "md_Doxygen_InterfaceMATLAB.html#autotoc_md41", null ],
    [ "Function tsgCopyGrid()", "md_Doxygen_InterfaceMATLAB.html#autotoc_md42", null ],
    [ "Function tsgWriteCustomRuleFile()", "md_Doxygen_InterfaceMATLAB.html#autotoc_md43", null ],
    [ "Function tsgExample()", "md_Doxygen_InterfaceMATLAB.html#autotoc_md44", null ],
    [ "GPU acceleration", "md_Doxygen_InterfaceMATLAB.html#autotoc_md45", null ],
    [ "Saving a Grid", "md_Doxygen_InterfaceMATLAB.html#autotoc_md46", null ],
    [ "Avoiding Some Problems", "md_Doxygen_InterfaceMATLAB.html#autotoc_md47", null ],
    [ "See the Included Examples", "md_Doxygen_InterfaceFortran2003.html#autotoc_md50", null ],
    [ "Row-vs-Column Format", "md_Doxygen_InterfaceFortran2003.html#autotoc_md51", null ],
    [ "Factory and Helper Methods and Namespaces", "md_Doxygen_InterfaceFortran2003.html#autotoc_md52", null ],
    [ "Complex numbers", "md_Doxygen_InterfaceFortran2003.html#autotoc_md53", null ],
    [ "MPI Fortran Capabilities", "md_Doxygen_InterfaceFortran2003.html#autotoc_md54", null ],
    [ "Tasmanian.hpp", "Tasmanian_8hpp.html", null ]
];