FROM nvidia/cuda:9.0-devel-ubuntu16.04

RUN apt-get update && apt-get install --no-install-recommends -y \
        libopenblas-dev \
        python \
        python-numpy \
        cmake \
        git \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
