FROM ubuntu:18.04

RUN apt update && apt install --no-install-recommends -y \
        build-essential \
        cmake \
        doxygen \
        graphviz \
        git \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
