/*
 * Copyright (c) 2017, Miroslav Stoyanov
 *
 * This file is part of
 * Toolkit for Adaptive Stochastic Modeling And Non-Intrusive ApproximatioN: TASMANIAN
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
 *    and the following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse
 *    or promote products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * UT-BATTELLE, LLC AND THE UNITED STATES GOVERNMENT MAKE NO REPRESENTATIONS AND DISCLAIM ALL WARRANTIES, BOTH EXPRESSED AND IMPLIED.
 * THERE ARE NO EXPRESS OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR THAT THE USE OF THE SOFTWARE WILL NOT INFRINGE ANY PATENT,
 * COPYRIGHT, TRADEMARK, OR OTHER PROPRIETARY RIGHTS, OR THAT THE SOFTWARE WILL ACCOMPLISH THE INTENDED RESULTS OR THAT THE SOFTWARE OR ITS USE WILL NOT RESULT IN INJURY OR DAMAGE.
 * THE USER ASSUMES RESPONSIBILITY FOR ALL LIABILITIES, PENALTIES, FINES, CLAIMS, CAUSES OF ACTION, AND COSTS AND EXPENSES, CAUSED BY, RESULTING FROM OR ARISING OUT OF,
 * IN WHOLE OR IN PART THE USE, STORAGE OR DISPOSAL OF THE SOFTWARE.
 */

#ifndef __TASMANIAN_ADDONS_HPP
#define __TASMANIAN_ADDONS_HPP

/*!
 * \internal
 * \file TasmanianAddons.hpp
 * \brief Header to include add addon templates.
 * \author Miroslav Stoyanov
 * \ingroup TasmanianAddons
 *
 * All addon templates are included with this single header.
 * \endinternal
 */

#include "tsgLoadUnstructuredPoints.hpp"
#include "tsgMPISampleDream.hpp"
#include "tsgExoticQuadrature.hpp"

/*!
 * \defgroup TasmanianAddons Additional Capabilities
 *
 * \par Extra Capabilities
 * The Addon module of Tasmanian offers a series of templates that offer
 * additional capabilities not necessarily included in the core modules.
 * The templates sit in a separate module for various reasons, e.g.,
 * - some methods are hard to classify or address fringe use cases
 * - the templates depend on third-party libraries and should not overwhelm
 *   the core modules with dependencies
 */

/*!
 * \defgroup TasmanianAddonsExoticQuad Exotic Quadrature
 * \ingroup TasmanianAddons
 *
 * \par Exotic Quadrature
 * The Exotic Quadrature module of Tasmanian offers a collection of functions for generating exotic quadrature rules in the form
 * of a TasGrid::CustomTabulated object. More specifically, these rules approximate the integral I := ∫ F(x) * weight_fn(x) dx by:
 *
 * I ≈ sum {f(roots[i]) * shifted_weights[i]} - shift * sum{f(correction_points[i]) * correction_weights[i]} over i,
 *
 * where, for a set of generated reference points ref_points[i], corresponding quadrature weights ref_weights[i], and level \b n,
 * we have:
 *
 *   (1) shift satisfies [weight_fn(x) + shift >= 0] for every x in the domain,
 *   (2) shifted_weights[i] = ref_weights[i] * (weight_fn(ref_points[i]) + shift) for every i,
 *   (3) correction_points and correction_weights are generated by a Gauss-Legendre rule with \b n nodes,
 *   (4) roots[i] is the i-th root of the n-th orthogonal polynomial with respect to weight_fn(), i.e., if p_k is the k-th
 *       orthogonal polynomial and k1 != k2, then ∫ p_k1(x) * p_k2(x) * weight_fn(x) dx = 0.
 */

#endif
