var searchData=
[
  ['factorize_0',['factorize',['../classTasGrid_1_1TasSparse_1_1WaveletBasisMatrix.html#a2697c9b23802ecc7fd94ef44130405c6',1,'TasGrid::TasSparse::WaveletBasisMatrix']]],
  ['factorizelq_1',['factorizeLQ',['../group__TasmanianTPLWrappers.html#ga73f075967add7e4ccc72d5c89d4d41e9',1,'TasBLAS']]],
  ['factorizeplu_2',['factorizePLU',['../namespaceTasGrid_1_1TasGpu.html#a596871ebd9203f0ad2e354baa4bfc3e1',1,'TasGrid::TasGpu']]],
  ['factory_20and_20helper_20methods_20and_20namespaces_3',['Factory and Helper Methods and Namespaces',['../md_Doxygen_2InterfaceFortran2003.html#autotoc_md61',1,'']]],
  ['fast_5ffourier_5ftransform_4',['fast_fourier_transform',['../group__TasmanianLinearSolvers.html#ga501f49479cce2a73870780c6bacbb805',1,'TasGrid::TasmanianFourierTransform']]],
  ['fast_5ffourier_5ftransform1d_5',['fast_fourier_transform1D',['../group__TasmanianLinearSolvers.html#ga2838be119d8f0a5e71d254f110bafad5',1,'TasGrid::TasmanianFourierTransform']]],
  ['favorsparse_6',['favorSparse',['../structTasGrid_1_1AccelerationContext.html#a316d48c2b352e1d6ffd515116cc2f231',1,'TasGrid::AccelerationContext']]],
  ['favorsparseacceleration_7',['favorSparseAcceleration',['../classTasGrid_1_1TasmanianSparseGrid.html#ac5ef3f5b8d4a0f34ca6466cc6e79c08c',1,'TasGrid::TasmanianSparseGrid']]],
  ['file_20format_8',['file format',['../md_Doxygen_2CustomRuleFileFormat.html',1,'Custom Rule File Format'],['../md_Doxygen_2InterfaceCLI.html#autotoc_md40',1,'Matrix File Format']]],
  ['filenames_20and_20strings_9',['Filenames and Strings',['../md_Doxygen_2InterfaceFortran2003.html#autotoc_md59',1,'']]],
  ['find_10',['find',['../classTasGrid_1_1CandidateManager.html#ac98bd06da8947d872949722e5dacc100',1,'TasGrid::CandidateManager']]],
  ['finishconstruction_11',['finishConstruction',['../classTasGrid_1_1TasmanianSparseGrid.html#a1b233fa0fb01f435e9a9c1aa2dfec420',1,'TasGrid::TasmanianSparseGrid']]],
  ['folder_20structure_12',['Install folder structure',['../md_Doxygen_2Installation.html#autotoc_md19',1,'']]],
  ['for_20acceleration_20methods_13',['Classes and functions used for acceleration methods',['../group__TasmanianAcceleration.html',1,'']]],
  ['for_20common_20i_20o_20methods_20simple_20binary_20ascii_20switch_20provided_20for_20all_20templates_14',['Templates for common I/O methods, simple binary/ascii switch provided for all templates',['../group__TasmanianIO.html',1,'']]],
  ['for_20dream_15',['MPI Send/Receive/Scatter for DREAM',['../group__TasmanianAddonsMPIDREAMSend.html',1,'']]],
  ['for_20gauuss_20chebyshev_20and_20custom_20rules_16',['Core meta-data for Gauuss, Chebyshev and custom rules',['../group__TasmanianCoreOneDimensional.html',1,'']]],
  ['for_20sparse_20grids_17',['MPI Send/Receive/Bcast/Scatter for Sparse Grids',['../group__TasmanianAddonsMPIGridSend.html',1,'']]],
  ['for_20the_20tasmanian_20dream_20module_18',['Examples for the Tasmanian DREAM module',['../group__TasmanianDREAMExamples.html',1,'']]],
  ['for_20the_20tasmanian_20optimization_20module_19',['Examples for the Tasmanian Optimization module',['../group__TasmanianOPTExamples.html',1,'']]],
  ['for_20the_20tasmanian_20sparse_20grid_20module_20',['Examples for the Tasmanian Sparse Grid module',['../group__TasmanianSGExamples.html',1,'']]],
  ['format_21',['format',['../md_Doxygen_2CustomRuleFileFormat.html',1,'Custom Rule File Format'],['../md_Doxygen_2InterfaceCLI.html#autotoc_md40',1,'Matrix File Format'],['../md_Doxygen_2InterfaceFortran2003.html#autotoc_md60',1,'Row-vs-Column Format']]],
  ['formcanonicalpoints_22',['formCanonicalPoints',['../classTasGrid_1_1TasmanianSparseGrid.html#a3daf055cf0cd2a590ca27482dc901a05',1,'TasGrid::TasmanianSparseGrid']]],
  ['formcanonicalpointsgpu_23',['formCanonicalPointsGPU',['../classTasGrid_1_1TasmanianSparseGrid.html#a0956195dcad90888e70c19976fe3beb1',1,'TasGrid::TasmanianSparseGrid']]],
  ['former_20contributors_24',['Former Contributors',['../md_Doxygen_2Contributors.html#autotoc_md9',1,'']]],
  ['formtransformedpoints_25',['formTransformedPoints',['../classTasGrid_1_1TasmanianSparseGrid.html#a1931d6c8c6a5542f362ac7babda015d8',1,'TasGrid::TasmanianSparseGrid']]],
  ['formulas_20and_20sampling_20algorithms_26',['Probability distributions, analytic formulas and sampling algorithms',['../group__DREAMPDF.html',1,'']]],
  ['fortran_202003_27',['Interface Fortran 2003',['../md_Doxygen_2InterfaceFortran2003.html',1,'']]],
  ['fortran_20capabilities_28',['MPI Fortran Capabilities',['../md_Doxygen_2InterfaceFortran2003.html#autotoc_md63',1,'']]],
  ['from_20posterior_29',['MPI Sampling from Posterior',['../group__TasmanianAddonsMPIDream.html',1,'']]],
  ['from_20tasgrid_30',['Miscellaneous utility templates, borrowed from TasGrid.',['../group__DREAMUtils.html',1,'']]],
  ['from_20unstructured_20point_20set_31',['Load from Unstructured Point Set',['../group__TasmanianAddonsLoadUnstructured.html',1,'']]],
  ['function_20tsgcleantempfiles_32',['Function tsgCleanTempFiles()',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md46',1,'']]],
  ['function_20tsgcopygrid_33',['Function tsgCopyGrid()',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md51',1,'']]],
  ['function_20tsgcoretests_34',['Function tsgCoreTests()',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md43',1,'']]],
  ['function_20tsgdeletegrid_20tsgdeletegridbyname_35',['Function tsgDeleteGrid()/tsgDeleteGridByName()',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md49',1,'']]],
  ['function_20tsgexample_36',['Function tsgExample()',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md53',1,'']]],
  ['function_20tsggetpaths_37',['Function tsgGetPaths()',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md44',1,'']]],
  ['function_20tsglistgridsbyname_38',['Function tsgListGridsByName()',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md47',1,'']]],
  ['function_20tsgloadgridfromfile_39',['Function tsgLoadGridFromFile()',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md48',1,'']]],
  ['function_20tsgreadmatrix_20and_20tsgwritematrix_40',['Function tsgReadMatrix() and tsgWriteMatrix()',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md45',1,'']]],
  ['function_20tsgreloadgrid_41',['Function tsgReloadGrid()',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md50',1,'']]],
  ['function_20tsgwritecustomrulefile_42',['Function tsgWriteCustomRuleFile()',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md52',1,'']]],
  ['functionality_43',['Wrappers around TPL functionality',['../group__TasmanianTPLWrappers.html',1,'']]],
  ['functions_44',['Commands and corresponding C++ functions',['../md_Doxygen_2InterfaceCLI.html#autotoc_md36',1,'']]],
  ['functions_20and_20aliases_45',['Miscellaneous utility functions and aliases',['../group__OptimizationUtil.html',1,'']]],
  ['functions_20and_20constants_46',['Math functions and constants',['../group__TasmanianMaths.html',1,'']]],
  ['functions_20and_20corresponding_20c_20api_47',['List of Matlab functions and corresponding C++ API',['../md_Doxygen_2InterfaceMATLAB.html#autotoc_md42',1,'']]],
  ['functions_20used_20for_20acceleration_20methods_48',['Classes and functions used for acceleration methods',['../group__TasmanianAcceleration.html',1,'']]]
];
