var dir_34eb90aa079dea8715dc1292570f23f1 =
[
    [ "Examples", "dir_2ce6b6da7abc757f04cbaf82faf7ae38.html", "dir_2ce6b6da7abc757f04cbaf82faf7ae38" ],
    [ "TasmanianSparseGrid.hpp", "TasmanianSparseGrid_8hpp.html", "TasmanianSparseGrid_8hpp" ],
    [ "tsgAcceleratedDataStructures.hpp", "tsgAcceleratedDataStructures_8hpp.html", "tsgAcceleratedDataStructures_8hpp" ],
    [ "tsgAcceleratedHandles.hpp", "tsgAcceleratedHandles_8hpp_source.html", null ],
    [ "tsgCacheLagrange.hpp", "tsgCacheLagrange_8hpp.html", null ],
    [ "tsgCoreOneDimensional.hpp", "tsgCoreOneDimensional_8hpp.html", "tsgCoreOneDimensional_8hpp" ],
    [ "tsgCudaLoadStructures.hpp", "tsgCudaLoadStructures_8hpp_source.html", null ],
    [ "tsgDConstructGridGlobal.hpp", "tsgDConstructGridGlobal_8hpp.html", "tsgDConstructGridGlobal_8hpp" ],
    [ "tsgEnumerates.hpp", "tsgEnumerates_8hpp.html", "tsgEnumerates_8hpp" ],
    [ "tsgGridCore.hpp", "tsgGridCore_8hpp.html", null ],
    [ "tsgGridFourier.hpp", "tsgGridFourier_8hpp_source.html", null ],
    [ "tsgGridGlobal.hpp", "tsgGridGlobal_8hpp_source.html", null ],
    [ "tsgGridLocalPolynomial.hpp", "tsgGridLocalPolynomial_8hpp.html", null ],
    [ "tsgGridSequence.hpp", "tsgGridSequence_8hpp_source.html", null ],
    [ "tsgGridWavelet.hpp", "tsgGridWavelet_8hpp_source.html", null ],
    [ "tsgHardCodedTabulatedRules.hpp", "tsgHardCodedTabulatedRules_8hpp.html", null ],
    [ "tsgHierarchyManipulator.hpp", "tsgHierarchyManipulator_8hpp.html", "tsgHierarchyManipulator_8hpp" ],
    [ "tsgIndexManipulator.hpp", "tsgIndexManipulator_8hpp.html", "tsgIndexManipulator_8hpp" ],
    [ "tsgIndexSets.hpp", "tsgIndexSets_8hpp.html", "tsgIndexSets_8hpp" ],
    [ "tsgIOHelpers.hpp", "tsgIOHelpers_8hpp.html", "tsgIOHelpers_8hpp" ],
    [ "tsgLinearSolvers.hpp", "tsgLinearSolvers_8hpp.html", "tsgLinearSolvers_8hpp" ],
    [ "tsgMathUtils.hpp", "tsgMathUtils_8hpp.html", "tsgMathUtils_8hpp" ],
    [ "tsgOneDimensionalWrapper.hpp", "tsgOneDimensionalWrapper_8hpp.html", null ],
    [ "tsgRuleLocalPolynomial.hpp", "tsgRuleLocalPolynomial_8hpp_source.html", null ],
    [ "tsgRuleWavelet.hpp", "tsgRuleWavelet_8hpp_source.html", null ],
    [ "tsgSequenceOptimizer.hpp", "tsgSequenceOptimizer_8hpp.html", "tsgSequenceOptimizer_8hpp" ],
    [ "tsgUtils.hpp", "tsgUtils_8hpp.html", "tsgUtils_8hpp" ]
];