var group__TasmanianSG =
[
    [ "Sparse Grid Class", "group__TasmanianSGClass.html", "group__TasmanianSGClass" ],
    [ "Enumerated types", "group__SGEnumerates.html", "group__SGEnumerates" ],
    [ "Miscellaneous utility templates", "group__TasmanianUtils.html", "group__TasmanianUtils" ],
    [ "Math functions and constants", "group__TasmanianMaths.html", "group__TasmanianMaths" ],
    [ "Multi-Index data structures", "group__TasmanianSets.html", "group__TasmanianSets" ],
    [ "Multi-Index manipulation algorithms", "group__TasmanianMultiIndexManipulations.html", "group__TasmanianMultiIndexManipulations" ],
    [ "Hierarchical multi-Index manipulation algorithms", "group__TasmanianHierarchyManipulations.html", "group__TasmanianHierarchyManipulations" ],
    [ "Templates for common I/O methods, simple binary/ascii switch provided for all templates", "group__TasmanianIO.html", "group__TasmanianIO" ],
    [ "Classes and functions used for acceleration methods", "group__TasmanianAcceleration.html", "group__TasmanianAcceleration" ],
    [ "Core meta-data for Gauuss, Chebyshev and custom rules", "group__TasmanianCoreOneDimensional.html", "group__TasmanianCoreOneDimensional" ],
    [ "Linear solvers", "group__TasmanianLinearSolvers.html", "group__TasmanianLinearSolvers" ],
    [ "Refinement related classes, structures, and methods", "group__TasmanianRefinement.html", "group__TasmanianRefinement" ],
    [ "Greedy Sequences", "group__TasmanianSequenceOpt.html", "group__TasmanianSequenceOpt" ],
    [ "TasmanianSparseGrid.hpp", "TasmanianSparseGrid_8hpp.html", null ],
    [ "TasGrid", "namespaceTasGrid.html", null ],
    [ "makeEmpty", "group__TasmanianSG.html#ga0269d4c5c5352ef1f92cdde67b6ffcd7", null ],
    [ "makeGlobalGrid", "group__TasmanianSG.html#ga734013b4f52c4d1d9a35d674b459e13a", null ],
    [ "makeSequenceGrid", "group__TasmanianSG.html#ga40cde16ae94c02a23271df606918cfb9", null ],
    [ "makeLocalPolynomialGrid", "group__TasmanianSG.html#gaaa84e44ca8145727564dbb57e7c939a3", null ],
    [ "makeWaveletGrid", "group__TasmanianSG.html#ga39d644b025ba40d9dcfa6af96a0c7dad", null ],
    [ "makeFourierGrid", "group__TasmanianSG.html#ga946aedd76d776e8669671026911755d1", null ],
    [ "readGrid", "group__TasmanianSG.html#ga7e2d073ce7e53d9b995be9550e320eb9", null ],
    [ "readGrid", "group__TasmanianSG.html#ga35006357632e3764f8b00eb8ad5f5daa", null ],
    [ "copyGrid", "group__TasmanianSG.html#gae7dff1a79964aa775e372b615e07ef44", null ],
    [ "mode_ascii", "group__TasmanianSG.html#gade99cdabcb4650a230ac1ef8c9ae1e22", null ],
    [ "mode_binary", "group__TasmanianSG.html#gab25913c6e0ddb0f1ef4a70c9c8cddc5b", null ]
];