var namespaceTasGrid =
[
    [ "AccHandle", "namespaceTasGrid_1_1AccHandle.html", "namespaceTasGrid_1_1AccHandle" ],
    [ "HierarchyManipulations", "namespaceTasGrid_1_1HierarchyManipulations.html", "namespaceTasGrid_1_1HierarchyManipulations" ],
    [ "IO", "namespaceTasGrid_1_1IO.html", "namespaceTasGrid_1_1IO" ],
    [ "MultiIndexManipulations", "namespaceTasGrid_1_1MultiIndexManipulations.html", "namespaceTasGrid_1_1MultiIndexManipulations" ],
    [ "Optimizer", null, [
      [ "CurrentNodes", "structTasGrid_1_1Optimizer_1_1CurrentNodes.html", "structTasGrid_1_1Optimizer_1_1CurrentNodes" ],
      [ "CurrentNodes< rule_leja >", "structTasGrid_1_1Optimizer_1_1CurrentNodes_3_01rule__leja_01_4.html", "structTasGrid_1_1Optimizer_1_1CurrentNodes_3_01rule__leja_01_4" ],
      [ "CurrentNodes< rule_mindeltaodd >", "structTasGrid_1_1Optimizer_1_1CurrentNodes_3_01rule__mindeltaodd_01_4.html", "structTasGrid_1_1Optimizer_1_1CurrentNodes_3_01rule__mindeltaodd_01_4" ],
      [ "HasDerivative", "structTasGrid_1_1Optimizer_1_1HasDerivative.html", null ],
      [ "HasDerivative< rule_mindelta >", "structTasGrid_1_1Optimizer_1_1HasDerivative_3_01rule__mindelta_01_4.html", null ],
      [ "HasDerivative< rule_minlebesgue >", "structTasGrid_1_1Optimizer_1_1HasDerivative_3_01rule__minlebesgue_01_4.html", null ],
      [ "OptimizerResult", "structTasGrid_1_1Optimizer_1_1OptimizerResult.html", "structTasGrid_1_1Optimizer_1_1OptimizerResult" ]
    ] ],
    [ "TasSparse", "namespaceTasGrid_1_1TasSparse.html", "namespaceTasGrid_1_1TasSparse" ],
    [ "Utils", "namespaceTasGrid_1_1Utils.html", "namespaceTasGrid_1_1Utils" ],
    [ "AccelerationContext", "structTasGrid_1_1AccelerationContext.html", "structTasGrid_1_1AccelerationContext" ],
    [ "AccelerationDomainTransform", "classTasGrid_1_1AccelerationDomainTransform.html", "classTasGrid_1_1AccelerationDomainTransform" ],
    [ "CacheLagrange", "classTasGrid_1_1CacheLagrange.html", "classTasGrid_1_1CacheLagrange" ],
    [ "CandidateManager", "classTasGrid_1_1CandidateManager.html", "classTasGrid_1_1CandidateManager" ],
    [ "CompleteStorage", "classTasGrid_1_1CompleteStorage.html", "classTasGrid_1_1CompleteStorage" ],
    [ "CustomTabulated", "classTasGrid_1_1CustomTabulated.html", "classTasGrid_1_1CustomTabulated" ],
    [ "Data2D", "classTasGrid_1_1Data2D.html", "classTasGrid_1_1Data2D" ],
    [ "DynamicConstructorDataGlobal", "classTasGrid_1_1DynamicConstructorDataGlobal.html", "classTasGrid_1_1DynamicConstructorDataGlobal" ],
    [ "GpuEngine", "structTasGrid_1_1GpuEngine.html", "structTasGrid_1_1GpuEngine" ],
    [ "GpuVector", "classTasGrid_1_1GpuVector.html", "classTasGrid_1_1GpuVector" ],
    [ "HandleDeleter", "structTasGrid_1_1HandleDeleter.html", "structTasGrid_1_1HandleDeleter" ],
    [ "MultiIndexSet", "classTasGrid_1_1MultiIndexSet.html", "classTasGrid_1_1MultiIndexSet" ],
    [ "NodeData", "structTasGrid_1_1NodeData.html", "structTasGrid_1_1NodeData" ],
    [ "OneDimensionalWrapper", "classTasGrid_1_1OneDimensionalWrapper.html", "classTasGrid_1_1OneDimensionalWrapper" ],
    [ "SimpleConstructData", "structTasGrid_1_1SimpleConstructData.html", "structTasGrid_1_1SimpleConstructData" ],
    [ "StorageSet", "classTasGrid_1_1StorageSet.html", "classTasGrid_1_1StorageSet" ],
    [ "TableGaussPatterson", "classTasGrid_1_1TableGaussPatterson.html", "classTasGrid_1_1TableGaussPatterson" ],
    [ "TasmanianSparseGrid", "classTasGrid_1_1TasmanianSparseGrid.html", "classTasGrid_1_1TasmanianSparseGrid" ],
    [ "TensorData", "structTasGrid_1_1TensorData.html", "structTasGrid_1_1TensorData" ],
    [ "VectorToStreamBuffer", "classTasGrid_1_1VectorToStreamBuffer.html", "classTasGrid_1_1VectorToStreamBuffer" ]
];